include: package:flutter_lints/flutter.yaml
linter:
 rules:
   - prefer_single_quotes
analyzer:
  # exclude:
  #   - "**/*.g.dart"
  #   - "**/*.freezed.dart"
  errors:
    invalid_annotation_target: ignore
    library_private_types_in_public_api: ignore
