// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBlLIn0ag6Ns-qI3r4QSP-r4bSoqvOjRGA',
    appId: '1:965574249277:web:459e7434d317e05dd09354',
    messagingSenderId: '965574249277',
    projectId: 'taskbunny-255a6',
    authDomain: 'taskbunny-255a6.firebaseapp.com',
    storageBucket: 'taskbunny-255a6.appspot.com',
    measurementId: 'G-PHV266GWJW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBGSqTpWTNyatTAh5XN7hNg8A2VVulo_nQ',
    appId: '1:965574249277:android:248fa6d8d4bef61fd09354',
    messagingSenderId: '965574249277',
    projectId: 'taskbunny-255a6',
    storageBucket: 'taskbunny-255a6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCzS0lk4KwlRqqdy-gsMRNXbCJKPeJFUw0',
    appId: '1:965574249277:ios:53cb582115195ed9d09354',
    messagingSenderId: '965574249277',
    projectId: 'taskbunny-255a6',
    storageBucket: 'taskbunny-255a6.appspot.com',
    androidClientId: '965574249277-b649c6qfmjqrvlfle0gber8p1qm63va8.apps.googleusercontent.com',
    iosClientId: '965574249277-jihgh8kbnkm8j2s5fcbumkolgl123k1t.apps.googleusercontent.com',
    iosBundleId: 'com.example.taskBunny',
  );

}